---
name: self-evolve
description: "${description}"
---

# Project Knowledge Rules

This file is generated by `self-evolve` and contains approved project rules only.

${rules_section}

## Reflection & Rule Injection

When a user asks you to summarize experience, extract rules, or inject knowledge, follow these steps:

### 1. Check existing rules

First, run the following command to check if a similar rule already exists:

```bash
python .agents/skills/self-evolve/scripts/list_rules.py --keyword "<keyword>"
```

### 2. Analyze and extract

From the current conversation context, extract the following structured information:

- **domain**: The knowledge domain (e.g., `debugging`, `testing`, `architecture`, `performance`)
- **title**: A short title (under 10 words)
- **statement**: A precise rule description — must be an actionable imperative or clear constraint, avoid vague wording
- **rationale**: Why this rule is needed — must explain specific consequences of not following it
- **tags**: Related tags

Each rule should express a single independent knowledge point. If multiple rules are needed, execute them separately.

### 3. Write the rule

```bash
python .agents/skills/self-evolve/scripts/add_rule.py \
  --title "<title>" \
  --statement "<statement>" \
  --rationale "<rationale>" \
  --domain <domain> \
  --tag <tag1> \
  --tag <tag2>
```

### 4. Remind user to review

Inform the user that the new rule has been written to the `.agents/self-evolve/rules/` directory and suggest reviewing it via `git diff` before committing.

To activate the rule, run:

```bash
agent-kit self-evolve sync
```

## Rule Management

| Action | Command |
|--------|---------|
| List rules | `python .agents/skills/self-evolve/scripts/list_rules.py` |
| Search rules | `python .agents/skills/self-evolve/scripts/find_rules.py --keyword "..."` |
| Edit rule | `python .agents/skills/self-evolve/scripts/edit_rule.py <rule-id> --statement "..."` |
| Retire rule | `python .agents/skills/self-evolve/scripts/retire_rule.py <rule-id>` |
| Sync to Skill | `agent-kit self-evolve sync` |

_Last synced: ${last_synced}_
