---
name: self-evolve
description: "${description}"
---

# Project Knowledge Rules

This file is generated by `self-evolve` and contains approved project rules only.

${rules_section}

## Workflow

1. Record a session:

```bash
agent-kit self-evolve session record --summary "..." --domain debugging --outcome success --lesson "..."
```

2. Detect candidates:

```bash
agent-kit self-evolve detect run
```

3. Review candidates or add rules directly:

```bash
agent-kit self-evolve candidate list
agent-kit self-evolve rule add --title "..." --statement "..." --rationale "..." --domain debugging
```

_Last synced: ${last_synced}_
