#!/usr/bin/env python3
"""Search rules from the catalog.json generated by sync. Zero dependencies."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def load_catalog(script_dir: Path) -> dict | None:
    catalog_path = script_dir.parent / "catalog.json"
    if not catalog_path.exists():
        return None
    try:
        return json.loads(catalog_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def filter_rules(
    catalog: dict,
    *,
    domain: str | None = None,
    tag: str | None = None,
    keyword: str | None = None,
) -> list[dict]:
    results = []
    for rule in catalog.get("rules", []):
        if domain and rule.get("domain") != domain:
            continue
        if tag and tag not in rule.get("tags", []):
            continue
        if keyword:
            needle = keyword.lower()
            haystack = " ".join([
                str(rule.get("title", "")),
                str(rule.get("statement", "")),
                str(rule.get("rationale", "")),
            ]).lower()
            if needle not in haystack:
                continue
        results.append(rule)
    return results


def print_stats(catalog: dict) -> None:
    summary = catalog.get("summary", {})
    print(f"Total rules: {summary.get('total_rules', 0)}")
    for domain, count in sorted(summary.get("domains", {}).items()):
        print(f"  {domain}: {count}")


def print_rules(rules: list[dict], *, detail: bool = False) -> None:
    for rule in rules:
        print(f"[{rule.get('id')}] {rule.get('title')} ({rule.get('domain')})")
        if detail:
            print(f"  Statement: {rule.get('statement', '')}")
            print(f"  Rationale: {rule.get('rationale', '')}")
            print(f"  Tags: {', '.join(rule.get('tags', [])) or 'none'}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Search self-evolve rules from catalog.")
    parser.add_argument("--domain", help="Filter by domain")
    parser.add_argument("--tag", help="Filter by tag")
    parser.add_argument("--keyword", help="Search in title/statement/rationale")
    parser.add_argument("--stats", action="store_true", help="Show statistics")
    parser.add_argument("--detail", action="store_true", help="Show full rule details")
    args = parser.parse_args()

    catalog = load_catalog(Path(__file__).resolve().parent)
    if catalog is None:
        print("No catalog.json found. Run 'agent-kit self-evolve sync' first.", file=sys.stderr)
        sys.exit(1)

    if args.stats or (not args.domain and not args.tag and not args.keyword):
        print_stats(catalog)
        return

    filtered = filter_rules(catalog, domain=args.domain, tag=args.tag, keyword=args.keyword)
    if not filtered:
        print("No matching rules.")
        return

    print_rules(filtered, detail=args.detail)


if __name__ == "__main__":
    main()
